# Copyright (c) 2020 Huawei Technologies Co., Ltd.
# Licensed under CC BY-NC-SA 4.0 (Attribution-NonCommercial-ShareAlike 4.0 International) (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode
#
# The code is released for academic research use only. For commercial use, please contact Huawei Technologies Co., Ltd.
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This file contains content licensed by https://github.com/xinntao/BasicSR/blob/master/LICENSE/LICENSE

#### general settings
name: train
use_tb_logger: true
model: NCSR
distortion: sr
scale: 4
gpu_ids: [ 0 ]
std: 0.05   #!!float 1e-20
mode: 'softflow'
LRnoise: true
prob: 1.0
lr: !!float 5e-6

#### datasets
datasets:
  train:
    name: CelebA_160_tr
    mode: LRHR_IMG
    dataroot_GT: TRAINDATA  ###IMAGE FOLDER
    #dataroot_LQ: datasets/DF2K-tr_X4.pklv4 ### do not need if mode == LRHR_IMG
    quant: 32

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 18
    GT_size: 160
    use_flip: true
    color: RGB
  val:
    name: CelebA_160_va
    mode: LRHR_PKL
    dataroot_GT: datasets/DIV2K-va.pklv4
    dataroot_LQ: datasets/DIV2K-va_X4.pklv4
    quant: 32
    n_max: 20

#### Test Settings
model_path:  pretrained_model/4X.pth

#### network structures
network_G:
  which_model_G: NCSRNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23
  upscale: 4
  train_RRDB: false
  train_RRDB_delay: 0.5

  flow:
    K: 16
    L: 3
    S: [ 0, 16, 16 ]
    noInitialInj: true
    std_channels: 3
    coupling: CondAffineSeparatedAndCond
    additionalFlowNoAffine: 2
    split:
      enable: true
    fea_up0: true
    stackRRDB:
      blocks: [ 1, 8, 15, 22 ]
      concat: true

#### path
path:
  pretrain_model_G: pretrained_model/RRDB_DF2K_4X.pth
  strict_load: true
  resume_state: auto

#### training settings: learning rate scheme, loss
train:
  manual_seed: 10
  lr_G: !!float 2e-4
  weight_decay_G: 0
  beta1: 0.9
  beta2: 0.99
  lr_scheme: MultiStepLR
  warmup_iter: -1  # no warm up
  lr_steps_rel: [ 0.5, 0.75, 0.9, 0.95 ]
  lr_gamma: 0.5
  
  weight_l1: 0.00

  niter: 220000
  val_freq: 1000

#### validation settings
val:
  heats: [ 0.0, 0.5, 0.75, 1.0 ]
  n_sample: 3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e3
